# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Produto.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Produto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rProduto.proto\x12\x05proto\"V\n\x07Produto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05preco\x18\x03 \x01(\x02\x12\x11\n\tcategoria\x18\x04 \x01(\t\x12\x0f\n\x07\x65stoque\x18\x05 \x01(\x05\"7\n\x14\x41\x64icionarProdutoArgs\x12\x1f\n\x07produto\x18\x01 \x01(\x0b\x32\x0e.proto.Produto\"\x14\n\x12ListarProdutosArgs\"`\n\x11\x45\x64itarProdutoArgs\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05preco\x18\x03 \x01(\x02\x12\x11\n\tcategoria\x18\x04 \x01(\t\x12\x0f\n\x07\x65stoque\x18\x05 \x01(\x05\" \n\x12RemoverProdutoArgs\x12\n\n\x02id\x18\x01 \x01(\x05\"3\n\x0fGenericResponse\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\x05\x12\x10\n\x08mensagem\x18\x02 \x01(\t\":\n\x16ListarProdutosResponse\x12 \n\x08produtos\x18\x01 \x03(\x0b\x32\x0e.proto.Produto\"0\n\x11\x41\x64\x64ProductRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05preco\x18\x02 \x01(\x02\"6\n\x12\x41\x64\x64ProductResponse\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\x05\x12\x10\n\x08mensagem\x18\x02 \x01(\t\":\n\x16ListAllProductResponse\x12 \n\x08produtos\x18\x01 \x03(\x0b\x32\x0e.proto.Produto\"^\n\x07Message\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x14\n\x0cobfReference\x18\x03 \x01(\t\x12\x10\n\x08methodId\x18\x04 \x01(\t\x12\x11\n\targuments\x18\x05 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Produto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUTO']._serialized_start=24
  _globals['_PRODUTO']._serialized_end=110
  _globals['_ADICIONARPRODUTOARGS']._serialized_start=112
  _globals['_ADICIONARPRODUTOARGS']._serialized_end=167
  _globals['_LISTARPRODUTOSARGS']._serialized_start=169
  _globals['_LISTARPRODUTOSARGS']._serialized_end=189
  _globals['_EDITARPRODUTOARGS']._serialized_start=191
  _globals['_EDITARPRODUTOARGS']._serialized_end=287
  _globals['_REMOVERPRODUTOARGS']._serialized_start=289
  _globals['_REMOVERPRODUTOARGS']._serialized_end=321
  _globals['_GENERICRESPONSE']._serialized_start=323
  _globals['_GENERICRESPONSE']._serialized_end=374
  _globals['_LISTARPRODUTOSRESPONSE']._serialized_start=376
  _globals['_LISTARPRODUTOSRESPONSE']._serialized_end=434
  _globals['_ADDPRODUCTREQUEST']._serialized_start=436
  _globals['_ADDPRODUCTREQUEST']._serialized_end=484
  _globals['_ADDPRODUCTRESPONSE']._serialized_start=486
  _globals['_ADDPRODUCTRESPONSE']._serialized_end=540
  _globals['_LISTALLPRODUCTRESPONSE']._serialized_start=542
  _globals['_LISTALLPRODUCTRESPONSE']._serialized_end=600
  _globals['_MESSAGE']._serialized_start=602
  _globals['_MESSAGE']._serialized_end=696
# @@protoc_insertion_point(module_scope)
